name: meal-assistant
networks:
    default:
        driver: bridge
services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    expose:
      - "8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
